// Copyright(c) 2016 Guus Waals (guus_waals@live.nl)
// Licensed under the MIT License(MIT)
// See "LICENSE.txt" for more information

using osu.Framework.Audio.Track;

namespace osu.Framework.Audio
{
    /// <summary>
    /// Class that processed the audio generated by an audio track
    /// </summary>
    public abstract unsafe class Dsp
    {
        public AudioTrack Track { get; internal set; }

        public virtual void OnAdded()
        {
        }

        public virtual void OnRemoved()
        {
        }

        /// <summary>
        /// Process some sample
        /// </summary>
        /// <param name="buffer">Sample data</param>
        /// <param name="numSamples">Number of samples to process</param>
        public abstract void Process(float* buffer, int numSamples);
    }
}